# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rem',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
