# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-23 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0002_rem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rem',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
